name: fastapi-crud
services:
  fastapi:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mongodb://mongodb:27017
      - secret=dev
  mongodb:
    image: annamariapl/fastapi-crud:latest
    ports:
      - 27017
    volumes:
      - /annamariapl/mongodb
