name: fastapi-crud
services:
  fastapi:
    public: true
    image: annamariapl/fastapi-crud:latest
    build: .
    replicas: 1
    environment:
      - DB_HOST=mongodb://localhost:27017
      - secret=dev
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi
