name: CRUD App Preview Deployment

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: Login
      uses: okteto/login@main
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Create namespace
      uses: okteto/bend-annamariapl@main
      with:
        namespace: pr-${{ github.event.number }}-annamariapl
   
    - name: Deploy application
      uses: okteto/deploy-stack@main
      with:
        build: "true"
        namespace: pr-${{ github.event.number }}-annamariapl

    - name: add comment to PR
      uses: okteto/notify-pr@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: "Preview environment available at https://fastapi-pr-${{ github.event.number }}-annamariapl.cloud.okteto.net" 
